name: "Update Version Tags Action"
description: "Automatically Update Version Tags on Push or Release for Semantic Versions"
author: "Shane"
branding:
  icon: "tag"
  color: "red"

inputs:
  prefix:
    description: "Tag Prefix"
    default: "v"
  major:
    description: "Update Major Tag"
    default: "true"
  minor:
    description: "Update Minor Tag"
    default: "true"
  tags:
    description: "Extra Tags"
  tag:
    description: "Target Tag"
  create:
    description: "Create Target Tag"
    default: "false"
  summary:
    description: "Add Summary to Job"
    default: "true"
  dry_run:
    description: "Dry Run"
    default: "false"
  token:
    description: "GitHub Token"
    default: "${{ github.token }}"

outputs:
  tags:
    description: "Parsed Tags"

runs:
  using: "node20"
  main: "dist/index.js"
