name: "Update Version Tags Action"
description: "Automatically Update Version Tags on Push or Release for Semantic Versions. Maintain Release, Major, Minor and Custom Tags."
author: "Shane"
branding:
  icon: "tag"
  color: "red"

inputs:
  prefix:
    description: "Tag Prefix"
    default: "v"
  major:
    description: "Update Major Tag"
    default: "true"
  minor:
    description: "Update Minor Tag"
    default: "true"
  release:
    description: "Update Release Tag"
    default: "false"
  tags:
    description: "Extra Tags"
  tag:
    description: "Target Tag"
  create:
    description: "Create Target Tag"
    default: "false"
  summary:
    description: "Add Summary to Job"
    default: "true"
  dry_run:
    description: "Dry Run"
    default: "false"
  token:
    description: "GitHub Token"
    default: "${{ github.token }}"

outputs:
  tags:
    description: "Comma Seperated String of Parsed Tags"
  semver:
    description: "Parsed Semantic Version JSON"

runs:
  using: "node24"
  main: "dist/index.js"
