name: "Update Version Tags Action"
description: "Update Version Tags on Push or Release for Semantic Versions"
author: "Shane"
branding:
  icon: "tag"
  color: "red"

inputs:
  prefix:
    description: "Tag Prefix"
    required: false
    default: "v"
  major:
    description: "Update Major Tag"
    required: false
    default: "true"
  minor:
    description: "Update Minor Tag"
    required: false
    default: "true"
  tags:
    description: "Extra Tags"
    required: false
  target:
    description: "Target Tag"
    required: false
  summary:
    description: "Results Summary"
    required: false
    default: "true"
  token:
    description: "GitHub Token"
    required: false
    default: ${{ github.token }}

outputs:
  sha:
    description: "Target SHA"
  tags:
    description: "Parsed Tags"

runs:
  using: "node20"
  main: "dist/index.js"
