name: "Draft Release"

on:
  workflow_dispatch:
  push:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft:
    name: "Draft Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Get Previous Tag"
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "TAG: ${TAG}"
          echo "name=${TAG}" >> "${GITHUB_OUTPUT}"

      - name: "Draft Release Action"
        id: draft
        uses: cssnr/draft-release-action@master
        with:
          semver: patch
          prerelease: false
          prefix: v
          previous_tag_name: ${{ steps.tag.outputs.name }}
          notes_strip_prefix: true

      - name: "Process Release Draft URL"
        run: |
          echo "url: ${{ steps.draft.outputs.url }}"
