name: "Release"

on:
  release:
    types: [published]

env:
  tag: "${{ github.ref_name || github.event.release.tag_name }}"
  source: source # directory name - master/main branch
  release: release # directory and branch name - release branch
  action: action.yml
  dist: dist

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: "Debug"
        continue-on-error: true
        run: |
          pwd
          echo "env.tag: ${{ env.tag }}"
          echo "env.source: ${{ env.source }}"
          echo "env.release: ${{ env.release }}"

      - name: "Checkout Source"
        uses: actions/checkout@v6
        with:
          path: ${{ env.source }}

      - name: "Setup Node"
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: "Run Build"
        working-directory: ${{ env.source }}
        run: |
          pwd
          npm ci

      - name: "Checkout Release"
        uses: actions/checkout@v6
        with:
          path: ${{ env.release }}
          ref: ${{ env.release }}

      - name: "Debug 1"
        continue-on-error: true
        run: |
          sha256sum "${{ env.source }}/${{ env.dist }}/index.js"
          sha256sum "${{ env.release }}/${{ env.dist }}/index.js"

      - name: "Copy Build"
        run: |
          cp "${{ env.source }}/${{ env.action }}" "${{ env.release }}/"
          rm -rf "${{ env.release }}/${{ env.dist }}"
          cp -r "${{ env.source }}/${{ env.dist }}" "${{ env.release }}/${{ env.dist }}"

      - name: "Debug 2"
        continue-on-error: true
        run: |
          sha256sum "${{ env.source }}/${{ env.dist }}/index.js"
          sha256sum "${{ env.release }}/${{ env.dist }}/index.js"

      - name: "Commit and Push"
        uses: suzuki-shunsuke/commit-action@06e3b49d4706498d325d29bd85adc82ecf2f5d8f # v1.0.0
        with:
          commit_message: ${{ env.tag }}
          branch: ${{ env.release }}
          root_dir: ${{ env.release }}
          fail_on_self_push: false
          app_id: ${{ vars.APP_CLIENT_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: "Create Tracking Tag"
        uses: cssnr/update-version-tags-action@v2
        with:
          major: false
          minor: false
          release: true
          prefix: "${{ github.event.release.target_commitish }}-"

      - name: "Update Version Tags"
        id: tags
        uses: cssnr/update-version-tags-action@v2
        with:
          ref: refs/heads/${{ env.release }}
          release: true
          prefix: "v"
          force: true

      - name: "Update Release Notes"
        continue-on-error: true
        uses: smashedr/update-release-notes-action@master
        with:
          location: "tail"
          actions: |
            tags: ${{ steps.tags.outputs.tags }}
            sha: ${{ steps.tags.outputs.sha }}

      - name: "Package Changelog"
        continue-on-error: true
        uses: cssnr/package-changelog-action@v2

      - name: "Send Failure Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
