name: "Tags"

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target Tag"

jobs:
  tags:
    name: "Tags"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Update Tags"
        uses: cssnr/update-version-tags-action@manual
        with:
          tag: ${{ inputs.target }}
          token: ${{ secrets.GH_PAT }}
